sftp:
  host: "sftp.px.bylinkr.com"
  port: "8422"
  user: "linkr"
  pass: "${secure::sftp.pass}"
  path: "upload/theu"
  file: "invoices.json" 
  fileH: "hoinaco.csv" 
  mypath: "upload/theu/Paulita/Prod"
  products: "products.csv"
   
http:
  port: "8081"  
