http:
  port:"8081"
   
sftp:
  host: "sftp.px.bylinkr.com"
  port: "8422"
  user: "linkr"
  pass: "linkr2026"
  path: "upload/theu"
  file: "invoices.json" 
  fileH: "hoinaco.csv" 
  mypath: "upload/theu/Paulita/Local"
  products: "products.csv"
   
  
